### ISSUE TITLE
TODO: KeyChecker Function

### ISSUE THREAD

**Issue by jShannon92** [jShannon92/CS-1-Final#1]
We need a function to check for key presses and return an integer to affect the move direction.

**Comment by Astyudo** [comment]
Solved

**Comment by jShannon92** [comment]
Awesome, looks pretty good. I never used enum before but that looks pretty useful. I'm having trouble compiling it. Could you post the compiler commands your using?

**Comment by jShannon92** [comment]
Never mind, I got it working.

**Comment by Astyudo** [comment]
Oops, sorry went out to eat didn't get your email in time, glad you got it
working though

**Comment by jShannon92** [comment]
I added a new commit (v0.0.8). Would you wanna work on either the random food/head/direction generators or the game over screen? If we call the random generators before the "while(gameOver == false)" loop and have that loop nested in another loop with the game over screen called after the "while(gameOver == false){" loop is finished the player can play over and over again.

while(true){
  randomfood
  randomhead
  randomdirection
  while(!gameOver){
    ...
  }
  gameOverScreen();
}

**Comment by Astyudo** [comment]
I can work on the food/head/direction generators and see what I can do

**Comment by Astyudo** [comment]
I also added the controls to the title screen
so players know how to move

**Comment by Astyudo** [comment]
I won't be able to work on the project until sunday night, I just got a
call from my uncle and I need to head down to Santa Ana tonight. Just
letting you know
